version: "2"
services:
  telegraf:
    container_name: telegraf
    image: telegraf
    network_mode: "host"
    volumes:
        - "./telegraf.conf:/etc/telegraf/telegraf.conf"
        - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
